version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk
  steps:
    - checkout
    - android/install-ndk:
        ndk-version: android-ndk-r19c # or any other version
    - run:
        name: update deps
        command: |
            git submodule init
            git submodule update
            ndk-build --version
    - run:
        name: build
        command: ndk-build
